# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.AccountChartsResource do
  @moduledoc """
  API calls for all endpoints tagged `AccountChartsResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  List all account charts
  Retrieves a list of all the available account charts.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.AccountChartWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_account_charts_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.AccountChartWrap.t} | {:error, Tesla.Env.t}
  def list_account_charts_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/accountcharts")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.AccountChartWrap{}}
    ])
  end
end
