# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.AssetFileConnectionResource do
  @moduledoc """
  API calls for all endpoints tagged `AssetFileConnectionResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create an asset file connection

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (CreateAssetFileConnection): asset file connection

  ### Returns

  - `{:ok, FortnoxEx.Model.AssetFileConnection.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_asset_file_connection_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.AssetFileConnection.t} | {:error, Tesla.Env.t}
  def create_asset_file_connection_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/assetfileconnections")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.AssetFileConnection{}}
    ])
  end

  @doc """
  Remove an asset file connection

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `file_id` (String.t): fileId
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_asset_file_connection_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete_asset_file_connection_resource(connection, file_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/assetfileconnections/#{file_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Retrieve a list of asset file connections
  The asset register can return a list of assets or a single asset. By specifying a FileId in the URL, a single asset will be returned. Not specifying a FileId will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.AssetFileConnectionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_all_asset_file_connection_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.AssetFileConnectionResponse.t} | {:error, Tesla.Env.t}
  def get_all_asset_file_connection_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/assetfileconnections")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.AssetFileConnectionResponse{}}
    ])
  end
end
