# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.AssetTypesResource do
  @moduledoc """
  API calls for all endpoints tagged `AssetTypesResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create an asset type

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `id` (integer()): id
  - `opts` (keyword): Optional parameters
    - `:body` (CreateAssetWrap): request

  ### Returns

  - `{:ok, FortnoxEx.Model.AssetTypeWrapSingle.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_asset_types_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, FortnoxEx.Model.AssetTypeWrapSingle.t} | {:error, Tesla.Env.t}
  def create_asset_types_resource(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/assets/types/#{id}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.AssetTypeWrapSingle{}}
    ])
  end

  @doc """
  Delete an asset type

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `id` (integer()): id
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_asset_types_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete_asset_types_resource(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/assets/types/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Retrieve a list of asset types

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.AssetTypeWrapList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_all_asset_types_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.AssetTypeWrapList.t} | {:error, Tesla.Env.t}
  def get_all_asset_types_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/assets/types/")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.AssetTypeWrapList{}}
    ])
  end

  @doc """
  Retrieve an asset type

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `id` (integer()): id
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.AssetTypeWrapSingle.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_asset_types_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, FortnoxEx.Model.AssetTypeWrapSingle.t} | {:error, Tesla.Env.t}
  def get_asset_types_resource(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/assets/types/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.AssetTypeWrapSingle{}}
    ])
  end

  @doc """
  Update an asset type

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `id` (integer()): id
  - `opts` (keyword): Optional parameters
    - `:body` (UpdateAssetWrap): request

  ### Returns

  - `{:ok, FortnoxEx.Model.AssetTypeWrapSingle.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_asset_types_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, FortnoxEx.Model.AssetTypeWrapSingle.t} | {:error, Tesla.Env.t}
  def update_asset_types_resource(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/assets/types/#{id}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.AssetTypeWrapSingle{}}
    ])
  end
end
