# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.CompanyInformationResource do
  @moduledoc """
  API calls for all endpoints tagged `CompanyInformationResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Retrieve the Company Information

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.CompanyInfoWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_company_information_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.CompanyInfoWrap.t} | {:error, Tesla.Env.t}
  def get_company_information_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/companyinformation")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.CompanyInfoWrap{}}
    ])
  end
end
