# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.CurrenciesResource do
  @moduledoc """
  API calls for all endpoints tagged `CurrenciesResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create a currency

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (CurrencyWrap): currency to create

  ### Returns

  - `{:ok, FortnoxEx.Model.CurrencyWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_currencies_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.CurrencyWrap.t} | {:error, Tesla.Env.t}
  def create_currencies_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/3/currencies")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.CurrencyWrap{}}
    ])
  end

  @doc """
  Retrieve a single currency

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies currency
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.CurrencyWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_currencies_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.CurrencyWrap.t} | {:error, Tesla.Env.t}
  def get_currencies_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/currencies/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.CurrencyWrap{}}
    ])
  end

  @doc """
  Retrieve a list of currencies
  The currency register can return a list of records or a single record. By specifying a Code in the URL, a single record will be returned. Not specifying a Code will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.CurrencyList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_currencies_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.CurrencyList.t} | {:error, Tesla.Env.t}
  def list_currencies_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/currencies")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.CurrencyList{}}
    ])
  end

  @doc """
  Remove a currency

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the currency
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_currencies_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_currencies_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/3/currencies/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Update a currency

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the currency
  - `opts` (keyword): Optional parameters
    - `:body` (CurrencyWrap): to update

  ### Returns

  - `{:ok, FortnoxEx.Model.CurrencyWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_currencies_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.CurrencyWrap.t} | {:error, Tesla.Env.t}
  def update_currencies_resource(connection, code, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/3/currencies/#{code}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.CurrencyWrap{}}
    ])
  end
end
