# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.CustomOutboundDocumentResource do
  @moduledoc """
  API calls for all endpoints tagged `CustomOutboundDocumentResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Get custom outbound document

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `type` (String.t): document type
  - `id` (String.t): document id
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.CustomOutboundDocument.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, FortnoxEx.Model.CustomOutboundDocument.t} | {:error, Tesla.Env.t}
  def get(connection, type, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/warehouse/documentdeliveries/custom/outbound-v1/#{type}/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.CustomOutboundDocument{}}
    ])
  end

  @doc """
  Release custom outbound document

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `type` (String.t): document type
  - `id` (String.t): document id
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec release(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def release(connection, type, id, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/warehouse/documentdeliveries/custom/outbound-v1/#{type}/#{id}/release")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Save a custom outbound document
  <br>  If type is not known, it will be registered as belonging to the OUTBOUND category.<br>  If type is an existing custom document type of category INBOUND an error is thrown.<br>  If type is invalid an error is thrown.<br>

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `type` (String.t): the type of the custom outbound document, min 1 character, max 25 characters, may contain letters A-Z, digits 0-9, underscore (_), and dash (-). Always stored as upper case.
  - `id` (String.t): the id of the custom outbound document, min 1 character, max 25 characters, may only contain digits 0-9
  - `opts` (keyword): Optional parameters
    - `:body` (CustomOutboundDocument): the <code>CustomOutboundDocument</code> to create

  ### Returns

  - `{:ok, FortnoxEx.Model.CustomOutboundDocument.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec save(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, FortnoxEx.Model.CustomOutboundDocument.t} | {:error, Tesla.Env.t}
  def save(connection, type, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/api/warehouse/documentdeliveries/custom/outbound-v1/#{type}/#{id}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.CustomOutboundDocument{}}
    ])
  end

  @doc """
  Void custom outbound document

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `type` (String.t): document type
  - `id` (String.t): document id
  - `opts` (keyword): Optional parameters
    - `:force` (boolean()): true if the document should be voided even if the document has connected outbounds, defaults to false.

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec void_document(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def void_document(connection, type, id, opts \\ []) do
    optional_params = %{
      :force => :query
    }

    request =
      %{}
      |> method(:put)
      |> url("/api/warehouse/documentdeliveries/custom/outbound-v1/#{type}/#{id}/void")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end
end
