# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.InvoiceAccrualsResource do
  @moduledoc """
  API calls for all endpoints tagged `InvoiceAccrualsResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create an invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (InvoiceAccrualWrap): invoice accrual to create

  ### Returns

  - `{:ok, FortnoxEx.Model.InvoiceAccrualWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_invoice_accruals_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.InvoiceAccrualWrap.t} | {:error, Tesla.Env.t}
  def create_invoice_accruals_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/3/invoiceaccruals/")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.InvoiceAccrualWrap{}}
    ])
  end

  @doc """
  Retrieve a single invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `invoice_number` (integer()): identifies the invoice accrual
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.InvoiceAccrualWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_invoice_accruals_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, FortnoxEx.Model.InvoiceAccrualWrap.t} | {:error, Tesla.Env.t}
  def get_invoice_accruals_resource(connection, invoice_number, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/invoiceaccruals/#{invoice_number}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.InvoiceAccrualWrap{}}
    ])
  end

  @doc """
  Retrieve a list of invoice accruals
  The invoice accruals register can return a list of records or a single record. By specifying a InvoiceNumber in the URL, a single record will be returned. Not specifying a InvoiceNumber will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.InvoiceAccrualListItemList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_invoice_accruals_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.InvoiceAccrualListItemList.t} | {:error, Tesla.Env.t}
  def list_invoice_accruals_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/invoiceaccruals/")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.InvoiceAccrualListItemList{}}
    ])
  end

  @doc """
  Remove an invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `invoice_number` (integer()): identifies the invoice accrual
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_invoice_accruals_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_invoice_accruals_resource(connection, invoice_number, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/3/invoiceaccruals/#{invoice_number}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Update an invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `invoice_number` (integer()): identifies the invoice accrual
  - `opts` (keyword): Optional parameters
    - `:body` (InvoiceAccrualWrap): invoice accrual to update

  ### Returns

  - `{:ok, FortnoxEx.Model.InvoiceAccrualWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_invoice_accruals_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, FortnoxEx.Model.InvoiceAccrualWrap.t} | {:error, Tesla.Env.t}
  def update_invoice_accruals_resource(connection, invoice_number, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/3/invoiceaccruals/#{invoice_number}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.InvoiceAccrualWrap{}}
    ])
  end
end
