# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.MeResource do
  @moduledoc """
  API calls for all endpoints tagged `MeResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Retrieve user information  Use this endpoint to retrieve user information related to the used access token

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.MeWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_me_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.MeWrap.t} | {:error, Tesla.Env.t}
  def get_me_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/me")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.MeWrap{}}
    ])
  end
end
