# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.PrintTemplatesResource do
  @moduledoc """
  API calls for all endpoints tagged `PrintTemplatesResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Retrieve a list of print templates

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.PrintTemplateList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_print_templates_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.PrintTemplateList.t} | {:error, Tesla.Env.t}
  def list_print_templates_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/printtemplates")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.PrintTemplateList{}}
    ])
  end
end
