# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.SupplierInvoiceAccrualsResource do
  @moduledoc """
  API calls for all endpoints tagged `SupplierInvoiceAccrualsResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create a supplier invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (SupplierInvoiceAccrualWrap): to create

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierInvoiceAccrualWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_supplier_invoice_accruals_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.SupplierInvoiceAccrualWrap.t} | {:error, Tesla.Env.t}
  def create_supplier_invoice_accruals_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/3/supplierinvoiceaccruals/")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierInvoiceAccrualWrap{}}
    ])
  end

  @doc """
  Retrieve a single supplier invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `supplier_invoice_number` (integer()): identifies the supplier invoice accrual
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierInvoiceAccrualWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_supplier_invoice_accruals_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, FortnoxEx.Model.SupplierInvoiceAccrualWrap.t} | {:error, Tesla.Env.t}
  def get_supplier_invoice_accruals_resource(connection, supplier_invoice_number, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/supplierinvoiceaccruals/#{supplier_invoice_number}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierInvoiceAccrualWrap{}}
    ])
  end

  @doc """
  Retrieve a list of supplier invoice accruals
  The supplier invoice accruals register can return a list of records or a single record. By specifying a SupplierInvoiceNumber in the URL, a single record will be returned. Not specifying a SupplierInvoiceNumber will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierInvoiceAccrualListItemList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_supplier_invoice_accruals_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.SupplierInvoiceAccrualListItemList.t} | {:error, Tesla.Env.t}
  def list_supplier_invoice_accruals_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/supplierinvoiceaccruals/")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierInvoiceAccrualListItemList{}}
    ])
  end

  @doc """
  Remove a supplier invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `supplier_invoice_number` (integer()): identifies the supplier invoice accrual
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_supplier_invoice_accruals_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_supplier_invoice_accruals_resource(connection, supplier_invoice_number, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/3/supplierinvoiceaccruals/#{supplier_invoice_number}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Update a supplier invoice accrual

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `supplier_invoice_number` (integer()): identifies the supplier invoice accrual
  - `opts` (keyword): Optional parameters
    - `:body` (SupplierInvoiceAccrualWrap): to update

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierInvoiceAccrualWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_supplier_invoice_accruals_resource(Tesla.Env.client, integer(), keyword()) :: {:ok, FortnoxEx.Model.SupplierInvoiceAccrualWrap.t} | {:error, Tesla.Env.t}
  def update_supplier_invoice_accruals_resource(connection, supplier_invoice_number, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/3/supplierinvoiceaccruals/#{supplier_invoice_number}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierInvoiceAccrualWrap{}}
    ])
  end
end
