# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.SupplierInvoiceFileConnectionsResource do
  @moduledoc """
  API calls for all endpoints tagged `SupplierInvoiceFileConnectionsResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create an supplier invoice file connection

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (SupplierInvoiceFileConnectionWrap): supplier invoice file connection to create

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierInvoiceFileConnectionWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_supplier_invoice_file_connections_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.SupplierInvoiceFileConnectionWrap.t} | {:error, Tesla.Env.t}
  def create_supplier_invoice_file_connections_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/supplierinvoicefileconnections/")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierInvoiceFileConnectionWrap{}}
    ])
  end

  @doc """
  Retrieve a single supplier invoice file connection

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `file_id` (String.t): identifies the file connection
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierInvoiceFileConnectionWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_supplier_invoice_file_connections_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.SupplierInvoiceFileConnectionWrap.t} | {:error, Tesla.Env.t}
  def get_supplier_invoice_file_connections_resource(connection, file_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/supplierinvoicefileconnections/#{file_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierInvoiceFileConnectionWrap{}}
    ])
  end

  @doc """
  Retrieve a list of supplier invoice file connections
  The supplier invoice file connections register can return a list of records or a single record. By specifying a FileId in the URL, a single record will be returned. Not specifying a FileId will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierInvoiceFileConnectionList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_supplier_invoice_file_connections_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.SupplierInvoiceFileConnectionList.t} | {:error, Tesla.Env.t}
  def list_supplier_invoice_file_connections_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/supplierinvoicefileconnections/")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierInvoiceFileConnectionList{}}
    ])
  end

  @doc """
  Remove an supplier invoice file connection

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `file_id` (String.t): identifies the supplier invoice file connection
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_supplier_invoice_file_connections_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_supplier_invoice_file_connections_resource(connection, file_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/supplierinvoicefileconnections/#{file_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end
end
