# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.SuppliersResource do
  @moduledoc """
  API calls for all endpoints tagged `SuppliersResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create a supplier

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (SupplierWrap): to create

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_suppliers_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.SupplierWrap.t} | {:error, Tesla.Env.t}
  def create_suppliers_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/suppliers")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierWrap{}}
    ])
  end

  @doc """
  Retrieve a single supplier

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `supplier_number` (String.t): identifies the supplier
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_suppliers_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.SupplierWrap.t} | {:error, Tesla.Env.t}
  def get_suppliers_resource(connection, supplier_number, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/suppliers/#{supplier_number}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierWrap{}}
    ])
  end

  @doc """
  Retrieve a list of suppliers
  The supplier register can return a list of records or a single record. By specifying a SupplierNumber in the URL, a single record will be returned. Not specifying a SupplierNumber will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierListItemList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_suppliers_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.SupplierListItemList.t} | {:error, Tesla.Env.t}
  def list_suppliers_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/suppliers")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierListItemList{}}
    ])
  end

  @doc """
  Update a supplier

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `supplier_number` (String.t): identifies the supplier
  - `opts` (keyword): Optional parameters
    - `:body` (SupplierWrap): to update

  ### Returns

  - `{:ok, FortnoxEx.Model.SupplierWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_suppliers_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.SupplierWrap.t} | {:error, Tesla.Env.t}
  def update_suppliers_resource(connection, supplier_number, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/suppliers/#{supplier_number}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.SupplierWrap{}}
    ])
  end
end
