# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.TermsOfPaymentsResource do
  @moduledoc """
  API calls for all endpoints tagged `TermsOfPaymentsResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create a term of payment

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (TermsOfPaymentWrap): to create

  ### Returns

  - `{:ok, FortnoxEx.Model.TermsOfPaymentWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_terms_of_payments_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.TermsOfPaymentWrap.t} | {:error, Tesla.Env.t}
  def create_terms_of_payments_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/3/termsofpayments")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.TermsOfPaymentWrap{}}
    ])
  end

  @doc """
  Retrieve a single terms of payment

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the terms of payment
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.TermsOfPaymentWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_terms_of_payments_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.TermsOfPaymentWrap.t} | {:error, Tesla.Env.t}
  def get_terms_of_payments_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/termsofpayments/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.TermsOfPaymentWrap{}}
    ])
  end

  @doc """
  Retrieve a list of all terms of payments

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.TermsOfPaymentList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_terms_of_payments_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.TermsOfPaymentList.t} | {:error, Tesla.Env.t}
  def list_terms_of_payments_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/termsofpayments")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.TermsOfPaymentList{}}
    ])
  end

  @doc """
  Remove a term of payment

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the terms of payment
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_terms_of_payments_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_terms_of_payments_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/3/termsofpayments/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Update a term of payment

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the term of payment
  - `opts` (keyword): Optional parameters
    - `:body` (TermsOfPaymentWrap): term of payment to update

  ### Returns

  - `{:ok, FortnoxEx.Model.TermsOfPaymentWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_terms_of_payments_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.TermsOfPaymentWrap.t} | {:error, Tesla.Env.t}
  def update_terms_of_payments_resource(connection, code, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/3/termsofpayments/#{code}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.TermsOfPaymentWrap{}}
    ])
  end
end
