# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.UnitsResource do
  @moduledoc """
  API calls for all endpoints tagged `UnitsResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create a unit

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (UnitWrap): to create

  ### Returns

  - `{:ok, FortnoxEx.Model.UnitWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_units_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.UnitWrap.t} | {:error, Tesla.Env.t}
  def create_units_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/3/units")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.UnitWrap{}}
    ])
  end

  @doc """
  Retrieve a single unit

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the unit
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.UnitWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_units_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.UnitWrap.t} | {:error, Tesla.Env.t}
  def get_units_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/units/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.UnitWrap{}}
    ])
  end

  @doc """
  Retrieve a list of units
  The units register can return a list of records or a single record. By specifying a Code in the URL, a single record will be returned. Not specifying a Code will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.UnitList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_units_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.UnitList.t} | {:error, Tesla.Env.t}
  def list_units_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/3/units")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.UnitList{}}
    ])
  end

  @doc """
  Remove a unit

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the unit
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_units_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_units_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/3/units/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Update a unit

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the unit
  - `opts` (keyword): Optional parameters
    - `:body` (UnitWrap): unit to update

  ### Returns

  - `{:ok, FortnoxEx.Model.UnitWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_units_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.UnitWrap.t} | {:error, Tesla.Env.t}
  def update_units_resource(connection, code, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/3/units/#{code}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.UnitWrap{}}
    ])
  end
end
