# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.VacationDebtBasisResource do
  @moduledoc """
  API calls for all endpoints tagged `VacationDebtBasisResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Retrieve a specific vacation debt basis for a posted voucher

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `year` (integer()):
  - `month` (integer()):
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.VacationDebtBasisWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_vacation_debt_basis_resource(Tesla.Env.client, integer(), integer(), keyword()) :: {:ok, FortnoxEx.Model.VacationDebtBasisWrap.t} | {:error, Tesla.Env.t}
  def get_vacation_debt_basis_resource(connection, year, month, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/vacationdebtbasis/#{year}/#{month}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.VacationDebtBasisWrap{}}
    ])
  end
end
