# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Api.WayOfDeliveriesResource do
  @moduledoc """
  API calls for all endpoints tagged `WayOfDeliveriesResource`.
  """

  alias FortnoxEx.Connection
  import FortnoxEx.RequestBuilder

  @doc """
  Create a way of delivery

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (WayOfDeliveryWrap): way of delivery to create

  ### Returns

  - `{:ok, FortnoxEx.Model.WayOfDeliveryWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_way_of_deliveries_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.WayOfDeliveryWrap.t} | {:error, Tesla.Env.t}
  def create_way_of_deliveries_resource(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/wayofdeliveries")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.WayOfDeliveryWrap{}}
    ])
  end

  @doc """
  Retrieve a single way of delivery

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the way of delivery
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.WayOfDeliveryWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_way_of_deliveries_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.WayOfDeliveryWrap.t} | {:error, Tesla.Env.t}
  def get_way_of_deliveries_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/wayofdeliveries/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.WayOfDeliveryWrap{}}
    ])
  end

  @doc """
  Retrieve a list of way of deliveries
  The way of delivery register can return a list of records or a single record. By specifying a Code in the URL, a single record will be returned. Not specifying a Code will return a list of records.

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, FortnoxEx.Model.WayOfDeliveryList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_way_of_deliveries_resource(Tesla.Env.client, keyword()) :: {:ok, FortnoxEx.Model.WayOfDeliveryList.t} | {:error, Tesla.Env.t}
  def list_way_of_deliveries_resource(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/wayofdeliveries")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.WayOfDeliveryList{}}
    ])
  end

  @doc """
  Remove a way of delivery

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the way of delivery
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_way_of_deliveries_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_way_of_deliveries_resource(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/wayofdeliveries/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {:default, false}
    ])
  end

  @doc """
  Update a way of delivery

  ### Parameters

  - `connection` (FortnoxEx.Connection): Connection to server
  - `code` (String.t): identifies the way of delivery
  - `opts` (keyword): Optional parameters
    - `:body` (WayOfDeliveryWrap): way of delivery to update

  ### Returns

  - `{:ok, FortnoxEx.Model.WayOfDeliveryWrap.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_way_of_deliveries_resource(Tesla.Env.client, String.t, keyword()) :: {:ok, FortnoxEx.Model.WayOfDeliveryWrap.t} | {:error, Tesla.Env.t}
  def update_way_of_deliveries_resource(connection, code, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/wayofdeliveries/#{code}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %FortnoxEx.Model.WayOfDeliveryWrap{}}
    ])
  end
end
