# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AbsenceTransactionListItemWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AbsenceTransactions
  ]

  @type t :: %__MODULE__{
    :AbsenceTransactions => [FortnoxEx.Model.AbsenceTransactionListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AbsenceTransactionListItemWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AbsenceTransactions, :list, FortnoxEx.Model.AbsenceTransactionListItem, options)
  end
end

