# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AbsenceTransactionListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :id,
    :EmployeeId,
    :CauseCode,
    :Date,
    :Extent,
    :Hours,
    :HolidayEntitling,
    :CostCenter,
    :Project
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :id => String.t | nil,
    :EmployeeId => String.t,
    :CauseCode => String.t,
    :Date => Date.t,
    :Extent => float() | nil,
    :Hours => float() | nil,
    :HolidayEntitling => boolean() | nil,
    :CostCenter => String.t | nil,
    :Project => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AbsenceTransactionListItem do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Date, :date, nil, options)
  end
end

