# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AbsenceTransactionSingleItemWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AbsenceTransaction
  ]

  @type t :: %__MODULE__{
    :AbsenceTransaction => FortnoxEx.Model.AbsenceTransactionSingleItem.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AbsenceTransactionSingleItemWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AbsenceTransaction, :struct, FortnoxEx.Model.AbsenceTransactionSingleItem, options)
  end
end

