# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AccountSingleItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :Active,
    :BalanceBroughtForward,
    :CostCenter,
    :CostCenterSettings,
    :Description,
    :Number,
    :Project,
    :ProjectSettings,
    :SRU,
    :Year,
    :VATCode,
    :BalanceCarriedForward,
    :TransactionInformation,
    :TransactionInformationSettings,
    :QuantitySettings,
    :QuantityUnit,
    :OpeningQuantities
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :Active => boolean() | nil,
    :BalanceBroughtForward => float() | nil,
    :CostCenter => String.t | nil,
    :CostCenterSettings => String.t | nil,
    :Description => String.t,
    :Number => integer(),
    :Project => String.t | nil,
    :ProjectSettings => String.t | nil,
    :SRU => integer() | nil,
    :Year => integer() | nil,
    :VATCode => String.t | nil,
    :BalanceCarriedForward => float() | nil,
    :TransactionInformation => String.t | nil,
    :TransactionInformationSettings => String.t | nil,
    :QuantitySettings => String.t | nil,
    :QuantityUnit => String.t | nil,
    :OpeningQuantities => [FortnoxEx.Model.AccountSingleItemOpeningQuantities.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AccountSingleItem do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:OpeningQuantities, :list, FortnoxEx.Model.AccountSingleItemOpeningQuantities, options)
  end
end

