# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AccountSingleItemWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Account
  ]

  @type t :: %__MODULE__{
    :Account => FortnoxEx.Model.AccountSingleItem.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AccountSingleItemWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Account, :struct, FortnoxEx.Model.AccountSingleItem, options)
  end
end

