# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AccountListItemWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Accounts
  ]

  @type t :: %__MODULE__{
    :Accounts => [FortnoxEx.Model.AccountListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AccountListItemWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Accounts, :list, FortnoxEx.Model.AccountListItem, options)
  end
end

