# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AccountPayloadOpeningQuantities do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Project,
    :Balance
  ]

  @type t :: %__MODULE__{
    :Project => String.t | nil,
    :Balance => integer() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AccountPayloadOpeningQuantities do
  def decode(value, _options) do
    value
  end
end

