# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ArticleFileConnection do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :FileId,
    :ArticleNumber
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :FileId => String.t,
    :ArticleNumber => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ArticleFileConnection do
  def decode(value, _options) do
    value
  end
end

