# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ArticleFileConnectionListItemWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ArticleFileConnections
  ]

  @type t :: %__MODULE__{
    :ArticleFileConnections => [FortnoxEx.Model.ArticleFileConnectionListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ArticleFileConnectionListItemWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ArticleFileConnections, :list, FortnoxEx.Model.ArticleFileConnectionListItem, options)
  end
end

