# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ArticleListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :ArticleNumber,
    :Description,
    :DisposableQuantity,
    :EAN,
    :Housework,
    :PurchasePrice,
    :SalesPrice,
    :QuantityInStock,
    :ReservedQuantity,
    :StockPlace,
    :StockValue,
    :Unit,
    :VAT,
    :WebshopArticle
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :ArticleNumber => String.t | nil,
    :Description => String.t,
    :DisposableQuantity => String.t | nil,
    :EAN => String.t | nil,
    :Housework => boolean() | nil,
    :PurchasePrice => String.t | nil,
    :SalesPrice => String.t | nil,
    :QuantityInStock => float() | nil,
    :ReservedQuantity => String.t | nil,
    :StockPlace => String.t | nil,
    :StockValue => String.t | nil,
    :Unit => String.t | nil,
    :VAT => String.t | nil,
    :WebshopArticle => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ArticleListItem do
  def decode(value, _options) do
    value
  end
end

