# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ArticleFileConnectionWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ArticleFileConnection
  ]

  @type t :: %__MODULE__{
    :ArticleFileConnection => FortnoxEx.Model.ArticleFileConnection.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ArticleFileConnectionWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ArticleFileConnection, :struct, FortnoxEx.Model.ArticleFileConnection, options)
  end
end

