# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AssetTypeWrapSingle do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type
  ]

  @type t :: %__MODULE__{
    :Type => FortnoxEx.Model.AssetType.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AssetTypeWrapSingle do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Type, :struct, FortnoxEx.Model.AssetType, options)
  end
end

