# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AssetSingle do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Assets
  ]

  @type t :: %__MODULE__{
    :Assets => FortnoxEx.Model.Asset.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AssetSingle do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Assets, :struct, FortnoxEx.Model.Asset, options)
  end
end

