# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AssetTypeWrapList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :MetaInformation,
    :Types
  ]

  @type t :: %__MODULE__{
    :MetaInformation => FortnoxEx.Model.MetaInformation.t | nil,
    :Types => [FortnoxEx.Model.AssetType.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AssetTypeWrapList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:MetaInformation, :struct, FortnoxEx.Model.MetaInformation, options)
    |> deserialize(:Types, :list, FortnoxEx.Model.AssetType, options)
  end
end

