# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AttendanceTransactionWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AttendanceTransaction
  ]

  @type t :: %__MODULE__{
    :AttendanceTransaction => FortnoxEx.Model.AttendanceTransaction.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AttendanceTransactionWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AttendanceTransaction, :struct, FortnoxEx.Model.AttendanceTransaction, options)
  end
end

