# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AttendanceTransaction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EmployeeId,
    :CauseCode,
    :Date,
    :Hours,
    :CostCenter,
    :Project
  ]

  @type t :: %__MODULE__{
    :EmployeeId => String.t,
    :CauseCode => String.t,
    :Date => Date.t,
    :Hours => String.t | nil,
    :CostCenter => String.t | nil,
    :Project => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AttendanceTransaction do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Date, :date, nil, options)
  end
end

