# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AttendanceTransactionListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AttendanceTransactions
  ]

  @type t :: %__MODULE__{
    :AttendanceTransactions => [FortnoxEx.Model.AttendanceTransactionListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AttendanceTransactionListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AttendanceTransactions, :list, FortnoxEx.Model.AttendanceTransactionListItem, options)
  end
end

