# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.AverageCost do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :itemId,
    :stockPointId,
    :averageCostInSEK
  ]

  @type t :: %__MODULE__{
    :itemId => String.t | nil,
    :stockPointId => String.t | nil,
    :averageCostInSEK => float() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.AverageCost do
  def decode(value, _options) do
    value
  end
end

