# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CompanyInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Address,
    :City,
    :CountryCode,
    :DatabaseNumber,
    :CompanyName,
    :OrganizationNumber,
    :VisitAddress,
    :VisitCity,
    :VisitCountryCode,
    :VisitZipCode,
    :ZipCode
  ]

  @type t :: %__MODULE__{
    :Address => String.t | nil,
    :City => String.t | nil,
    :CountryCode => String.t | nil,
    :DatabaseNumber => integer() | nil,
    :CompanyName => String.t | nil,
    :OrganizationNumber => String.t | nil,
    :VisitAddress => String.t | nil,
    :VisitCity => String.t | nil,
    :VisitCountryCode => String.t | nil,
    :VisitZipCode => String.t | nil,
    :ZipCode => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CompanyInfo do
  def decode(value, _options) do
    value
  end
end

