# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ContractAccrualListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :Description,
    :DocumentNumber,
    :Period
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :Description => String.t,
    :DocumentNumber => integer(),
    :Period => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ContractAccrualListItem do
  def decode(value, _options) do
    value
  end
end

