# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ContractAccrual do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :AccrualAccount,
    :CostAccount,
    :Description,
    :AccrualRows,
    :DocumentNumber,
    :Period,
    :Times,
    :Total,
    :VATIncluded
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :AccrualAccount => integer(),
    :CostAccount => integer(),
    :Description => String.t,
    :AccrualRows => [FortnoxEx.Model.ContractAccrualAccrualRow.t],
    :DocumentNumber => integer(),
    :Period => String.t | nil,
    :Times => integer() | nil,
    :Total => float(),
    :VATIncluded => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ContractAccrual do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AccrualRows, :list, FortnoxEx.Model.ContractAccrualAccrualRow, options)
  end
end

