# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ContractTemplateListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :ContractLength,
    :ContractTemplate,
    :ContractTemplateName,
    :InvoiceInterval
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :ContractLength => integer() | nil,
    :ContractTemplate => integer() | nil,
    :ContractTemplateName => String.t | nil,
    :InvoiceInterval => integer() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ContractTemplateListItem do
  def decode(value, _options) do
    value
  end
end

