# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ContractWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Contract
  ]

  @type t :: %__MODULE__{
    :Contract => FortnoxEx.Model.Contract.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ContractWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Contract, :struct, FortnoxEx.Model.Contract, options)
  end
end

