# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CostCenterList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :CostCenters
  ]

  @type t :: %__MODULE__{
    :CostCenters => [FortnoxEx.Model.CostCenter.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CostCenterList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:CostCenters, :list, FortnoxEx.Model.CostCenter, options)
  end
end

