# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CreateAssetWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AssetType
  ]

  @type t :: %__MODULE__{
    :AssetType => FortnoxEx.Model.CreateAsset.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CreateAssetWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AssetType, :struct, FortnoxEx.Model.CreateAsset, options)
  end
end

