# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CreateAsset do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Number,
    :Description,
    :Notes,
    :Type,
    :AccountAssetId,
    :AccountDepreciationId,
    :AccountValueLossId
  ]

  @type t :: %__MODULE__{
    :Number => String.t | nil,
    :Description => String.t | nil,
    :Notes => String.t | nil,
    :Type => integer() | nil,
    :AccountAssetId => integer() | nil,
    :AccountDepreciationId => integer() | nil,
    :AccountValueLossId => integer() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CreateAsset do
  def decode(value, _options) do
    value
  end
end

