# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CurrencyList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Currencies
  ]

  @type t :: %__MODULE__{
    :Currencies => [FortnoxEx.Model.Currency.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CurrencyList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Currencies, :list, FortnoxEx.Model.Currency, options)
  end
end

