# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CustomDocumentType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :referenceType,
    :category
  ]

  @type t :: %__MODULE__{
    :referenceType => String.t,
    :category => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CustomDocumentType do
  def decode(value, _options) do
    value
  end
end

