# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CustomerReferenceWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :CustomerReference
  ]

  @type t :: %__MODULE__{
    :CustomerReference => FortnoxEx.Model.CustomerReference.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CustomerReferenceWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:CustomerReference, :struct, FortnoxEx.Model.CustomerReference, options)
  end
end

