# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CustomerDefaultDeliveryTypes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Invoice,
    :Order,
    :Offer
  ]

  @type t :: %__MODULE__{
    :Invoice => String.t | nil,
    :Order => String.t | nil,
    :Offer => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CustomerDefaultDeliveryTypes do
  def decode(value, _options) do
    value
  end
end

