# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CustomOutboundDocument do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :referenceType,
    :date,
    :note,
    :warehouseReady,
    :voided,
    :rows,
    :forcedDelivery,
    :averageCosts,
    :deliveryState
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :referenceType => String.t | nil,
    :date => Date.t,
    :note => String.t | nil,
    :warehouseReady => boolean() | nil,
    :voided => boolean() | nil,
    :rows => [FortnoxEx.Model.CustomOutboundDocumentRow.t],
    :forcedDelivery => boolean() | nil,
    :averageCosts => [FortnoxEx.Model.AverageCost.t] | nil,
    :deliveryState => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CustomOutboundDocument do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
    |> deserialize(:rows, :list, FortnoxEx.Model.CustomOutboundDocumentRow, options)
    |> deserialize(:averageCosts, :list, FortnoxEx.Model.AverageCost, options)
  end
end

