# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.CustomerWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Customer
  ]

  @type t :: %__MODULE__{
    :Customer => FortnoxEx.Model.Customer.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CustomerWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Customer, :struct, FortnoxEx.Model.Customer, options)
  end
end

