# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.Depreciation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :DepreciateUntil,
    :AssetIds
  ]

  @type t :: %__MODULE__{
    :DepreciateUntil => String.t | nil,
    :AssetIds => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.Depreciation do
  def decode(value, _options) do
    value
  end
end

