# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.DepreciationResponseWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AssetsDepreciation
  ]

  @type t :: %__MODULE__{
    :AssetsDepreciation => [FortnoxEx.Model.DepreciationResponse.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.DepreciationResponseWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AssetsDepreciation, :list, FortnoxEx.Model.DepreciationResponse, options)
  end
end

