# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.EmployeeWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Employee
  ]

  @type t :: %__MODULE__{
    :Employee => FortnoxEx.Model.Employee.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.EmployeeWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Employee, :struct, FortnoxEx.Model.Employee, options)
  end
end

