# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.EmployeeDatedSchedule do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EmployeeId,
    :FirstDay,
    :ScheduleId
  ]

  @type t :: %__MODULE__{
    :EmployeeId => String.t,
    :FirstDay => Date.t,
    :ScheduleId => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.EmployeeDatedSchedule do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:FirstDay, :date, nil, options)
  end
end

