# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.EuVatLimitRegulation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :TotalExclVat,
    :IsOverLimit,
    :Limit,
    :Year
  ]

  @type t :: %__MODULE__{
    :TotalExclVat => float() | nil,
    :IsOverLimit => boolean() | nil,
    :Limit => integer() | nil,
    :Year => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.EuVatLimitRegulation do
  def decode(value, _options) do
    value
  end
end

