# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ExpenseListItemWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Expenses
  ]

  @type t :: %__MODULE__{
    :Expenses => [FortnoxEx.Model.ExpenseListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ExpenseListItemWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Expenses, :list, FortnoxEx.Model.ExpenseListItem, options)
  end
end

