# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ExpenseListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Code,
    :Text,
    :Account,
    :@url
  ]

  @type t :: %__MODULE__{
    :Code => String.t,
    :Text => String.t,
    :Account => integer(),
    :@url => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ExpenseListItem do
  def decode(value, _options) do
    value
  end
end

