# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ExpenseWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Expense
  ]

  @type t :: %__MODULE__{
    :Expense => FortnoxEx.Model.Expense.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ExpenseWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Expense, :struct, FortnoxEx.Model.Expense, options)
  end
end

