# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.FinancialYear do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :Id,
    :FromDate,
    :ToDate,
    :AccountingMethod,
    :accountCharts
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :Id => integer() | nil,
    :FromDate => Date.t,
    :ToDate => Date.t,
    :AccountingMethod => String.t | nil,
    :accountCharts => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.FinancialYear do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:FromDate, :date, nil, options)
    |> deserialize(:ToDate, :date, nil, options)
  end
end

