# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.FolderFileRow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :Comments,
    :Id,
    :Name,
    :Path,
    :Size,
    :ArchiveFileId
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :Comments => String.t | nil,
    :Id => String.t | nil,
    :Name => String.t | nil,
    :Path => String.t | nil,
    :Size => integer() | nil,
    :ArchiveFileId => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.FolderFileRow do
  def decode(value, _options) do
    value
  end
end

