# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.InvoiceAccrual do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :AccrualAccount,
    :Description,
    :EndDate,
    :InvoiceAccrualRows,
    :InvoiceNumber,
    :Period,
    :RevenueAccount,
    :StartDate,
    :Times,
    :Total,
    :VATIncluded
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :AccrualAccount => integer(),
    :Description => String.t,
    :EndDate => Date.t,
    :InvoiceAccrualRows => [FortnoxEx.Model.InvoiceAccrualInvoiceAccrualRow.t],
    :InvoiceNumber => integer(),
    :Period => String.t | nil,
    :RevenueAccount => integer(),
    :StartDate => Date.t,
    :Times => integer() | nil,
    :Total => float(),
    :VATIncluded => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.InvoiceAccrual do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:EndDate, :date, nil, options)
    |> deserialize(:InvoiceAccrualRows, :list, FortnoxEx.Model.InvoiceAccrualInvoiceAccrualRow, options)
    |> deserialize(:StartDate, :date, nil, options)
  end
end

