# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.InvoicePaymentListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :InvoicePayments
  ]

  @type t :: %__MODULE__{
    :InvoicePayments => [FortnoxEx.Model.InvoicePaymentListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.InvoicePaymentListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:InvoicePayments, :list, FortnoxEx.Model.InvoicePaymentListItem, options)
  end
end

