# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.InvoiceResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :BalanceIncludeFees,
    :BalanceIncludeFeesCurrency,
    :CurrentCapitalBalance,
    :CurrentCapitalBalanceCurrency,
    :InvoiceDocumentURL,
    :InvoiceNumber,
    :NextEvent,
    :NextEventDate,
    :OCRNumber,
    :Service,
    :ServiceName,
    :Status
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t,
    :BalanceIncludeFees => float(),
    :BalanceIncludeFeesCurrency => float(),
    :CurrentCapitalBalance => float(),
    :CurrentCapitalBalanceCurrency => float(),
    :InvoiceDocumentURL => String.t | nil,
    :InvoiceNumber => integer(),
    :NextEvent => String.t,
    :NextEventDate => Date.t,
    :OCRNumber => String.t,
    :Service => String.t,
    :ServiceName => String.t,
    :Status => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.InvoiceResponse do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:NextEventDate, :date, nil, options)
  end
end

