# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.InvoiceAccrualWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :InvoiceAccrual
  ]

  @type t :: %__MODULE__{
    :InvoiceAccrual => FortnoxEx.Model.InvoiceAccrual.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.InvoiceAccrualWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:InvoiceAccrual, :struct, FortnoxEx.Model.InvoiceAccrual, options)
  end
end

