# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.InvoiceAccrualListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :InvoiceAccruals
  ]

  @type t :: %__MODULE__{
    :InvoiceAccruals => [FortnoxEx.Model.InvoiceAccrualListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.InvoiceAccrualListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:InvoiceAccruals, :list, FortnoxEx.Model.InvoiceAccrualListItem, options)
  end
end

