# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.LabelWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Label
  ]

  @type t :: %__MODULE__{
    :Label => FortnoxEx.Model.Label.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.LabelWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Label, :struct, FortnoxEx.Model.Label, options)
  end
end

