# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.LabelList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Labels
  ]

  @type t :: %__MODULE__{
    :Labels => [FortnoxEx.Model.Label.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.LabelList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Labels, :list, FortnoxEx.Model.Label, options)
  end
end

