# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ListAsset do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :Id,
    :Number,
    :Description,
    :Status,
    :StatusId,
    :Type,
    :TypeId,
    :AcquisitionValue,
    :AcquisitionDate,
    :DepreciationFinal,
    :DepreciatedTo
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :Id => integer() | nil,
    :Number => String.t | nil,
    :Description => String.t | nil,
    :Status => String.t | nil,
    :StatusId => String.t | nil,
    :Type => String.t | nil,
    :TypeId => integer() | nil,
    :AcquisitionValue => integer() | nil,
    :AcquisitionDate => String.t | nil,
    :DepreciationFinal => String.t | nil,
    :DepreciatedTo => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ListAsset do
  def decode(value, _options) do
    value
  end
end

