# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ManualObAsset do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Amount,
    :Comment
  ]

  @type t :: %__MODULE__{
    :Amount => integer() | nil,
    :Comment => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ManualObAsset do
  def decode(value, _options) do
    value
  end
end

