# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.MeWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :MeInformation
  ]

  @type t :: %__MODULE__{
    :MeInformation => FortnoxEx.Model.Me.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.MeWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:MeInformation, :struct, FortnoxEx.Model.Me, options)
  end
end

