# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.OfferWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Offer
  ]

  @type t :: %__MODULE__{
    :Offer => FortnoxEx.Model.Offer.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.OfferWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Offer, :struct, FortnoxEx.Model.Offer, options)
  end
end

