# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.OfferListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Offers
  ]

  @type t :: %__MODULE__{
    :Offers => [FortnoxEx.Model.OfferListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.OfferListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Offers, :list, FortnoxEx.Model.OfferListItem, options)
  end
end

