# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PausePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :PausedUntilDate
  ]

  @type t :: %__MODULE__{
    :PausedUntilDate => Date.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PausePayload do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PausedUntilDate, :date, nil, options)
  end
end

