# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PredefinedAccountWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :PreDefinedAccount
  ]

  @type t :: %__MODULE__{
    :PreDefinedAccount => FortnoxEx.Model.PredefinedAccount.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PredefinedAccountWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PreDefinedAccount, :struct, FortnoxEx.Model.PredefinedAccount, options)
  end
end

