# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PredefinedAccountList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :PreDefinedAccounts
  ]

  @type t :: %__MODULE__{
    :PreDefinedAccounts => [FortnoxEx.Model.PredefinedAccount.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PredefinedAccountList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PreDefinedAccounts, :list, FortnoxEx.Model.PredefinedAccount, options)
  end
end

