# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PredefinedVoucherSeriesWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :PreDefinedVoucherSeries
  ]

  @type t :: %__MODULE__{
    :PreDefinedVoucherSeries => FortnoxEx.Model.PredefinedVoucherSeries.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PredefinedVoucherSeriesWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PreDefinedVoucherSeries, :struct, FortnoxEx.Model.PredefinedVoucherSeries, options)
  end
end

