# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PredefinedVoucherSeries do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :Name,
    :VoucherSeries
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :Name => String.t | nil,
    :VoucherSeries => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PredefinedVoucherSeries do
  def decode(value, _options) do
    value
  end
end

