# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.Price do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :ArticleNumber,
    :Date,
    :FromQuantity,
    :Percent,
    :Price,
    :PriceList
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :ArticleNumber => String.t,
    :Date => DateTime.t | nil,
    :FromQuantity => float() | nil,
    :Percent => float() | nil,
    :Price => float() | nil,
    :PriceList => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.Price do
  def decode(value, _options) do
    value
  end
end

