# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PriceWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Price
  ]

  @type t :: %__MODULE__{
    :Price => FortnoxEx.Model.Price.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PriceWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Price, :struct, FortnoxEx.Model.Price, options)
  end
end

