# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PriceListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :ArticleNumber,
    :FromQuantity,
    :PriceList,
    :Price
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :ArticleNumber => String.t,
    :FromQuantity => float() | nil,
    :PriceList => String.t,
    :Price => float() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PriceListItem do
  def decode(value, _options) do
    value
  end
end

