# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ProjectListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Projects
  ]

  @type t :: %__MODULE__{
    :Projects => [FortnoxEx.Model.ProjectListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ProjectListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Projects, :list, FortnoxEx.Model.ProjectListItem, options)
  end
end

