# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ProjectWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Project
  ]

  @type t :: %__MODULE__{
    :Project => FortnoxEx.Model.Project.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ProjectWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Project, :struct, FortnoxEx.Model.Project, options)
  end
end

