# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PurchaseOrderMailSettings do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :receiver,
    :receiverCopy,
    :receiverSecretCopy,
    :subject,
    :body,
    :bodyAsHtml,
    :replyTo,
    :senderName
  ]

  @type t :: %__MODULE__{
    :receiver => String.t,
    :receiverCopy => String.t | nil,
    :receiverSecretCopy => String.t | nil,
    :subject => String.t,
    :body => String.t,
    :bodyAsHtml => String.t | nil,
    :replyTo => String.t,
    :senderName => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PurchaseOrderMailSettings do
  def decode(value, _options) do
    value
  end
end

