# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.PurchaseOrderRowNote do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :note,
    :rowNum,
    :purchaseOrderId,
    :purchaseOrderRowId
  ]

  @type t :: %__MODULE__{
    :note => String.t | nil,
    :rowNum => integer() | nil,
    :purchaseOrderId => integer() | nil,
    :purchaseOrderRowId => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.PurchaseOrderRowNote do
  def decode(value, _options) do
    value
  end
end

