# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.RegistrationCode do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :name,
    :priceMultiplier,
    :costMultiplier,
    :type,
    :active,
    :id
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :name => String.t | nil,
    :priceMultiplier => float() | nil,
    :costMultiplier => float() | nil,
    :type => String.t,
    :active => boolean() | nil,
    :id => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.RegistrationCode do
  def decode(value, _options) do
    value
  end
end

