# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ReportPaymentPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ClientTakesFees,
    :BookkeepPaymentInFortnox,
    :ReportToFinance,
    :PaymentAmount,
    :PaymentMethodCode,
    :PaymentMethodAccount
  ]

  @type t :: %__MODULE__{
    :ClientTakesFees => boolean(),
    :BookkeepPaymentInFortnox => boolean(),
    :ReportToFinance => boolean(),
    :PaymentAmount => float(),
    :PaymentMethodCode => String.t,
    :PaymentMethodAccount => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ReportPaymentPayload do
  def decode(value, _options) do
    value
  end
end

