# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ResponseStateChange do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :responseState
  ]

  @type t :: %__MODULE__{
    :responseState => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ResponseStateChange do
  def decode(value, _options) do
    value
  end
end

