# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SalaryTransactionListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :SalaryTransactions
  ]

  @type t :: %__MODULE__{
    :SalaryTransactions => [FortnoxEx.Model.SalaryTransactionListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SalaryTransactionListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:SalaryTransactions, :list, FortnoxEx.Model.SalaryTransactionListItem, options)
  end
end

