# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SalaryTransaction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EmployeeId,
    :SalaryCode,
    :SalaryRow,
    :Date,
    :Number,
    :Amount,
    :Total,
    :Expense,
    :VAT,
    :TextRow,
    :CostCenter,
    :Project
  ]

  @type t :: %__MODULE__{
    :EmployeeId => String.t,
    :SalaryCode => String.t,
    :SalaryRow => integer() | nil,
    :Date => Date.t,
    :Number => String.t | nil,
    :Amount => String.t | nil,
    :Total => String.t | nil,
    :Expense => String.t | nil,
    :VAT => String.t | nil,
    :TextRow => String.t | nil,
    :CostCenter => String.t | nil,
    :Project => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SalaryTransaction do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Date, :date, nil, options)
  end
end

