# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ScheduleTime do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EmployeeId,
    :Date,
    :ScheduleId,
    :Hours,
    :IWH1,
    :IWH2,
    :IWH3,
    :IWH4,
    :IWH5
  ]

  @type t :: %__MODULE__{
    :EmployeeId => String.t | nil,
    :Date => Date.t | nil,
    :ScheduleId => String.t | nil,
    :Hours => String.t | nil,
    :IWH1 => String.t | nil,
    :IWH2 => String.t | nil,
    :IWH3 => String.t | nil,
    :IWH4 => String.t | nil,
    :IWH5 => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ScheduleTime do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Date, :date, nil, options)
  end
end

