# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.ScheduleTimeWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ScheduleTime
  ]

  @type t :: %__MODULE__{
    :ScheduleTime => FortnoxEx.Model.ScheduleTime.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.ScheduleTimeWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ScheduleTime, :struct, FortnoxEx.Model.ScheduleTime, options)
  end
end

