# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.Sell do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Percentage,
    :Price,
    :Comment,
    :Date
  ]

  @type t :: %__MODULE__{
    :Percentage => integer() | nil,
    :Price => integer() | nil,
    :Comment => String.t | nil,
    :Date => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.Sell do
  def decode(value, _options) do
    value
  end
end

