# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.StockTakingRow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :stockTakingId,
    :itemId,
    :stockPointId,
    :stockLocationId,
    :countedBy,
    :stockTakenQuantity,
    :totalQuantityInStock,
    :currentRowNo,
    :hasPostReleaseStockChanges,
    :stockTakingRowId
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :stockTakingId => integer() | nil,
    :itemId => String.t | nil,
    :stockPointId => String.t | nil,
    :stockLocationId => String.t | nil,
    :countedBy => String.t | nil,
    :stockTakenQuantity => float() | nil,
    :totalQuantityInStock => float() | nil,
    :currentRowNo => integer() | nil,
    :hasPostReleaseStockChanges => boolean() | nil,
    :stockTakingRowId => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.StockTakingRow do
  def decode(value, _options) do
    value
  end
end

