# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.StockTaking do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :date,
    :name,
    :responsible,
    :state,
    :rows,
    :sortingId,
    :projectId,
    :costCenterCode,
    :usingStockPoints
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :date => Date.t | nil,
    :name => String.t,
    :responsible => String.t,
    :state => String.t,
    :rows => [FortnoxEx.Model.StockTakingRow.t] | nil,
    :sortingId => integer() | nil,
    :projectId => String.t | nil,
    :costCenterCode => String.t | nil,
    :usingStockPoints => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.StockTaking do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
    |> deserialize(:rows, :list, FortnoxEx.Model.StockTakingRow, options)
  end
end

