# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.StockLocation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :code,
    :name,
    :stockPointId
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :code => String.t,
    :name => String.t | nil,
    :stockPointId => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.StockLocation do
  def decode(value, _options) do
    value
  end
end

