# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.StockBalance do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :itemId,
    :availableStock,
    :inStock,
    :stockPointCode
  ]

  @type t :: %__MODULE__{
    :itemId => String.t | nil,
    :availableStock => float() | nil,
    :inStock => float() | nil,
    :stockPointCode => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.StockBalance do
  def decode(value, _options) do
    value
  end
end

