# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceSupplierInvoiceRow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Account,
    :ArticleNumber,
    :Code,
    :CostCenter,
    :AccountDescription,
    :ItemDescription,
    :Debit,
    :DebitCurrency,
    :Credit,
    :CreditCurrency,
    :Project,
    :TransactionInformation,
    :Price,
    :Quantity,
    :Total,
    :Unit,
    :StockPointCode,
    :StockLocationCode
  ]

  @type t :: %__MODULE__{
    :Account => integer() | nil,
    :ArticleNumber => String.t | nil,
    :Code => String.t | nil,
    :CostCenter => String.t | nil,
    :AccountDescription => String.t | nil,
    :ItemDescription => String.t | nil,
    :Debit => float() | nil,
    :DebitCurrency => float() | nil,
    :Credit => float() | nil,
    :CreditCurrency => float() | nil,
    :Project => String.t | nil,
    :TransactionInformation => String.t | nil,
    :Price => float() | nil,
    :Quantity => integer() | nil,
    :Total => float() | nil,
    :Unit => String.t | nil,
    :StockPointCode => String.t | nil,
    :StockLocationCode => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceSupplierInvoiceRow do
  def decode(value, _options) do
    value
  end
end

