# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Supplier
  ]

  @type t :: %__MODULE__{
    :Supplier => FortnoxEx.Model.Supplier.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Supplier, :struct, FortnoxEx.Model.Supplier, options)
  end
end

