# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :Balance,
    :Booked,
    :Cancel,
    :CostCenter,
    :Credit,
    :Currency,
    :CurrencyRate,
    :CurrencyUnit,
    :DueDate,
    :ExternalInvoiceNumber,
    :ExternalInvoiceSeries,
    :GivenNumber,
    :InvoiceDate,
    :InvoiceNumber,
    :Project,
    :SupplierNumber,
    :SupplierName,
    :Total,
    :AuthorizerName,
    :Vouchers,
    :FinalPayDate
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :Balance => String.t | nil,
    :Booked => boolean() | nil,
    :Cancel => boolean() | nil,
    :CostCenter => String.t | nil,
    :Credit => boolean() | nil,
    :Currency => String.t | nil,
    :CurrencyRate => String.t | nil,
    :CurrencyUnit => float() | nil,
    :DueDate => Date.t | nil,
    :ExternalInvoiceNumber => String.t | nil,
    :ExternalInvoiceSeries => String.t | nil,
    :GivenNumber => String.t | nil,
    :InvoiceDate => Date.t | nil,
    :InvoiceNumber => String.t | nil,
    :Project => String.t | nil,
    :SupplierNumber => String.t,
    :SupplierName => String.t | nil,
    :Total => String.t | nil,
    :AuthorizerName => String.t | nil,
    :Vouchers => [FortnoxEx.Model.SupplierInvoiceListItemVoucher.t] | nil,
    :FinalPayDate => Date.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceListItem do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:DueDate, :date, nil, options)
    |> deserialize(:InvoiceDate, :date, nil, options)
    |> deserialize(:Vouchers, :list, FortnoxEx.Model.SupplierInvoiceListItemVoucher, options)
    |> deserialize(:FinalPayDate, :date, nil, options)
  end
end

