# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceListItemVoucher do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Number,
    :Year,
    :Series,
    :ReferenceType
  ]

  @type t :: %__MODULE__{
    :Number => integer() | nil,
    :Year => integer() | nil,
    :Series => String.t | nil,
    :ReferenceType => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceListItemVoucher do
  def decode(value, _options) do
    value
  end
end

