# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoicePayment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :Amount,
    :AmountCurrency,
    :Booked,
    :Currency,
    :CurrencyRate,
    :CurrencyUnit,
    :Information,
    :InvoiceNumber,
    :InvoiceDueDate,
    :InvoiceOCR,
    :InvoiceSupplierName,
    :InvoiceSupplierNumber,
    :InvoiceTotal,
    :ModeOfPayment,
    :Number,
    :PaymentDate,
    :Source,
    :VoucherNumber,
    :VoucherSeries,
    :VoucherYear,
    :WriteOffs
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :Amount => float() | nil,
    :AmountCurrency => float() | nil,
    :Booked => boolean() | nil,
    :Currency => String.t | nil,
    :CurrencyRate => float() | nil,
    :CurrencyUnit => float() | nil,
    :Information => String.t | nil,
    :InvoiceNumber => String.t,
    :InvoiceDueDate => Date.t | nil,
    :InvoiceOCR => String.t | nil,
    :InvoiceSupplierName => String.t | nil,
    :InvoiceSupplierNumber => String.t | nil,
    :InvoiceTotal => String.t | nil,
    :ModeOfPayment => String.t | nil,
    :Number => integer() | nil,
    :PaymentDate => Date.t | nil,
    :Source => String.t | nil,
    :VoucherNumber => integer() | nil,
    :VoucherSeries => String.t | nil,
    :VoucherYear => integer() | nil,
    :WriteOffs => [FortnoxEx.Model.SupplierInvoicePaymentWriteOff.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoicePayment do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:InvoiceDueDate, :date, nil, options)
    |> deserialize(:PaymentDate, :date, nil, options)
    |> deserialize(:WriteOffs, :list, FortnoxEx.Model.SupplierInvoicePaymentWriteOff, options)
  end
end

