# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceAccrualListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :Description,
    :SupplierInvoiceNumber,
    :Period
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :Description => String.t | nil,
    :SupplierInvoiceNumber => integer() | nil,
    :Period => String.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceAccrualListItem do
  def decode(value, _options) do
    value
  end
end

