# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceFileConnectionWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :SupplierInvoiceFileConnection
  ]

  @type t :: %__MODULE__{
    :SupplierInvoiceFileConnection => FortnoxEx.Model.SupplierInvoiceFileConnection.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceFileConnectionWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:SupplierInvoiceFileConnection, :struct, FortnoxEx.Model.SupplierInvoiceFileConnection, options)
  end
end

