# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceExternalUrlConnection do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Url,
    :Id,
    :SupplierInvoiceNumber,
    :ExternalUrlConnection
  ]

  @type t :: %__MODULE__{
    :Url => String.t | nil,
    :Id => integer() | nil,
    :SupplierInvoiceNumber => integer() | nil,
    :ExternalUrlConnection => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceExternalUrlConnection do
  def decode(value, _options) do
    value
  end
end

