# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceAccrualListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :SupplierInvoiceAccruals
  ]

  @type t :: %__MODULE__{
    :SupplierInvoiceAccruals => [FortnoxEx.Model.SupplierInvoiceAccrualListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceAccrualListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:SupplierInvoiceAccruals, :list, FortnoxEx.Model.SupplierInvoiceAccrualListItem, options)
  end
end

