# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.SupplierInvoiceFileConnectionList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :SupplierInvoiceFileConnections
  ]

  @type t :: %__MODULE__{
    :SupplierInvoiceFileConnections => [FortnoxEx.Model.SupplierInvoiceFileConnection.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.SupplierInvoiceFileConnectionList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:SupplierInvoiceFileConnections, :list, FortnoxEx.Model.SupplierInvoiceFileConnection, options)
  end
end

