# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.TaxReductionListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :TaxReductions
  ]

  @type t :: %__MODULE__{
    :TaxReductions => [FortnoxEx.Model.TaxReductionListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.TaxReductionListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TaxReductions, :list, FortnoxEx.Model.TaxReductionListItem, options)
  end
end

