# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.TaxReduction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :ApprovedAmount,
    :AskedAmount,
    :BilledAmount,
    :CustomerName,
    :Id,
    :PropertyDesignation,
    :ReferenceDocumentType,
    :ReferenceNumber,
    :RequestSent,
    :ResidenceAssociationOrganisationNumber,
    :SocialSecurityNumber,
    :TypeOfReduction,
    :VoucherNumber,
    :VoucherSeries,
    :VoucherYear,
    :TaxReductionAmounts
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :ApprovedAmount => float() | nil,
    :AskedAmount => float(),
    :BilledAmount => float() | nil,
    :CustomerName => String.t,
    :Id => integer() | nil,
    :PropertyDesignation => String.t | nil,
    :ReferenceDocumentType => String.t,
    :ReferenceNumber => String.t,
    :RequestSent => boolean() | nil,
    :ResidenceAssociationOrganisationNumber => String.t | nil,
    :SocialSecurityNumber => String.t,
    :TypeOfReduction => String.t | nil,
    :VoucherNumber => integer() | nil,
    :VoucherSeries => String.t | nil,
    :VoucherYear => integer() | nil,
    :TaxReductionAmounts => [FortnoxEx.Model.TaxReductionTaxReductionAmount.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.TaxReduction do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TaxReductionAmounts, :list, FortnoxEx.Model.TaxReductionTaxReductionAmount, options)
  end
end

