# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.TermsOfDeliveryList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :TermsOfDeliveries
  ]

  @type t :: %__MODULE__{
    :TermsOfDeliveries => [FortnoxEx.Model.TermsOfDelivery.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.TermsOfDeliveryList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TermsOfDeliveries, :list, FortnoxEx.Model.TermsOfDelivery, options)
  end
end

