# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.TrCustomer do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :number,
    :active,
    :deleted,
    :priceList,
    :accountManager,
    :defaultProjectId,
    :isBusiness,
    :propertyDesignation
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :number => String.t | nil,
    :active => boolean() | nil,
    :deleted => boolean() | nil,
    :priceList => String.t | nil,
    :accountManager => String.t | nil,
    :defaultProjectId => String.t | nil,
    :isBusiness => integer() | nil,
    :propertyDesignation => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.TrCustomer do
  def decode(value, _options) do
    value
  end
end

