# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.TrItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :description,
    :active,
    :purchasePrice,
    :salesPrices,
    :type,
    :unit,
    :isStock
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :description => String.t | nil,
    :active => boolean() | nil,
    :purchasePrice => float() | nil,
    :salesPrices => [FortnoxEx.Model.TrItemPrice.t] | nil,
    :type => String.t | nil,
    :unit => String.t | nil,
    :isStock => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.TrItem do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:salesPrices, :list, FortnoxEx.Model.TrItemPrice, options)
  end
end

