# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.TrustedEmailSender do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :TrustedSenders,
    :RejectedSenders
  ]

  @type t :: %__MODULE__{
    :TrustedSenders => [FortnoxEx.Model.TrustedEmailSenderTrustedSender.t] | nil,
    :RejectedSenders => [FortnoxEx.Model.TrustedEmailSenderRejectedSender.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.TrustedEmailSender do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TrustedSenders, :list, FortnoxEx.Model.TrustedEmailSenderTrustedSender, options)
    |> deserialize(:RejectedSenders, :list, FortnoxEx.Model.TrustedEmailSenderRejectedSender, options)
  end
end

