# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.TrustedEmailSenderWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EmailSenders
  ]

  @type t :: %__MODULE__{
    :EmailSenders => FortnoxEx.Model.TrustedEmailSender.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.TrustedEmailSenderWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:EmailSenders, :struct, FortnoxEx.Model.TrustedEmailSender, options)
  end
end

