# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.Unit do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :Code,
    :Description,
    :CodeEnglish
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :Code => String.t,
    :Description => String.t,
    :CodeEnglish => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.Unit do
  def decode(value, _options) do
    value
  end
end

