# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.UnitList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Units
  ]

  @type t :: %__MODULE__{
    :Units => [FortnoxEx.Model.Unit.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.UnitList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Units, :list, FortnoxEx.Model.Unit, options)
  end
end

