# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.UpdateAsset do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Description,
    :Notes
  ]

  @type t :: %__MODULE__{
    :Description => String.t | nil,
    :Notes => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.UpdateAsset do
  def decode(value, _options) do
    value
  end
end

