# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VacationDebtBasis do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Year,
    :Month,
    :LastDay,
    :VoucherNumber,
    :VoucherSeries,
    :VoucherYear,
    :Employees
  ]

  @type t :: %__MODULE__{
    :Year => integer(),
    :Month => integer(),
    :LastDay => Date.t | nil,
    :VoucherNumber => integer() | nil,
    :VoucherSeries => String.t | nil,
    :VoucherYear => integer() | nil,
    :Employees => [FortnoxEx.Model.VacationDebtBasisEmployee.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VacationDebtBasis do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:LastDay, :date, nil, options)
    |> deserialize(:Employees, :list, FortnoxEx.Model.VacationDebtBasisEmployee, options)
  end
end

