# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VoucherVoucherRow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Account,
    :CostCenter,
    :Credit,
    :Description,
    :Debit,
    :Project,
    :Removed,
    :TransactionInformation,
    :Quantity
  ]

  @type t :: %__MODULE__{
    :Account => integer(),
    :CostCenter => String.t | nil,
    :Credit => float() | nil,
    :Description => String.t | nil,
    :Debit => float() | nil,
    :Project => String.t | nil,
    :Removed => boolean() | nil,
    :TransactionInformation => String.t | nil,
    :Quantity => float() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VoucherVoucherRow do
  def decode(value, _options) do
    value
  end
end

