# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VoucherSeriesApprover do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Name
  ]

  @type t :: %__MODULE__{
    :Id => integer() | nil,
    :Name => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VoucherSeriesApprover do
  def decode(value, _options) do
    value
  end
end

