# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VoucherFileConnectionWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :VoucherFileConnection
  ]

  @type t :: %__MODULE__{
    :VoucherFileConnection => FortnoxEx.Model.VoucherFileConnection.t
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VoucherFileConnectionWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:VoucherFileConnection, :struct, FortnoxEx.Model.VoucherFileConnection, options)
  end
end

