# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VoucherListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Vouchers
  ]

  @type t :: %__MODULE__{
    :Vouchers => [FortnoxEx.Model.VoucherListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VoucherListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Vouchers, :list, FortnoxEx.Model.VoucherListItem, options)
  end
end

