# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VoucherSeries do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :Code,
    :Description,
    :Manual,
    :NextVoucherNumber,
    :Year,
    :Approver
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :Code => String.t,
    :Description => String.t | nil,
    :Manual => boolean() | nil,
    :NextVoucherNumber => integer() | nil,
    :Year => integer() | nil,
    :Approver => FortnoxEx.Model.VoucherSeriesApprover.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VoucherSeries do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Approver, :struct, FortnoxEx.Model.VoucherSeriesApprover, options)
  end
end

