# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VoucherListItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :@url,
    :Comments,
    :Description,
    :ReferenceNumber,
    :ReferenceType,
    :TransactionDate,
    :VoucherNumber,
    :VoucherSeries,
    :Year,
    :ApprovalState
  ]

  @type t :: %__MODULE__{
    :@url => String.t | nil,
    :Comments => String.t | nil,
    :Description => String.t | nil,
    :ReferenceNumber => String.t | nil,
    :ReferenceType => String.t | nil,
    :TransactionDate => Date.t | nil,
    :VoucherNumber => integer() | nil,
    :VoucherSeries => String.t | nil,
    :Year => integer() | nil,
    :ApprovalState => integer() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VoucherListItem do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TransactionDate, :date, nil, options)
  end
end

