# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.VoucherSeriesListItemList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :VoucherSeriesCollection
  ]

  @type t :: %__MODULE__{
    :VoucherSeriesCollection => [FortnoxEx.Model.VoucherSeriesListItem.t] | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.VoucherSeriesListItemList do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:VoucherSeriesCollection, :list, FortnoxEx.Model.VoucherSeriesListItem, options)
  end
end

