# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FortnoxEx.Model.WayOfDeliveryWrap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :WayOfDelivery
  ]

  @type t :: %__MODULE__{
    :WayOfDelivery => FortnoxEx.Model.WayOfDelivery.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.WayOfDeliveryWrap do
  import FortnoxEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:WayOfDelivery, :struct, FortnoxEx.Model.WayOfDelivery, options)
  end
end

